# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170818_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
