# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
